'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace DV_ASMX_Thu_nghiem
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap")>  _
    Public Interface XL_DICH_VU_ASMXSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dang_nhap_QLCT", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Dang_nhap_QLCT(ByVal Ten_Dang_nhap As String, ByVal Mat_khau As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dang_nhap_QLCT", ReplyAction:="*")>  _
        Function Dang_nhap_QLCTAsync(ByVal Ten_Dang_nhap As String, ByVal Mat_khau As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dang_nhap_QLCN", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Dang_nhap_QLCN(ByVal Ten_Dang_nhap As String, ByVal Mat_khau As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dang_nhap_QLCN", ReplyAction:="*")>  _
        Function Dang_nhap_QLCNAsync(ByVal Ten_Dang_nhap As String, ByVal Mat_khau As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Ghi_moi_Nhan_vien", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Ghi_moi_Nhan_vien(ByVal Du_lieu_He_khach As System.Data.DataSet) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Ghi_moi_Nhan_vien", ReplyAction:="*")>  _
        Function Ghi_moi_Nhan_vienAsync(ByVal Du_lieu_He_khach As System.Data.DataSet) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cap_nhat_Nhan_vien", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cap_nhat_Nhan_vien(ByVal Du_lieu_He_khach As System.Data.DataSet) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cap_nhat_Nhan_vien", ReplyAction:="*")>  _
        Function Cap_nhat_Nhan_vienAsync(ByVal Du_lieu_He_khach As System.Data.DataSet) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Xoa_Nhan_vien", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Xoa_Nhan_vien(ByVal Du_lieu_He_khach As System.Data.DataSet) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Xoa_Nhan_vien", ReplyAction:="*")>  _
        Function Xoa_Nhan_vienAsync(ByVal Du_lieu_He_khach As System.Data.DataSet) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface XL_DICH_VU_ASMXSoapChannel
        Inherits DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class XL_DICH_VU_ASMXSoapClient
        Inherits System.ServiceModel.ClientBase(Of DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)
        Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Dang_nhap_QLCT(ByVal Ten_Dang_nhap As String, ByVal Mat_khau As String) As System.Data.DataSet Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Dang_nhap_QLCT
            Return MyBase.Channel.Dang_nhap_QLCT(Ten_Dang_nhap, Mat_khau)
        End Function
        
        Public Function Dang_nhap_QLCTAsync(ByVal Ten_Dang_nhap As String, ByVal Mat_khau As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Dang_nhap_QLCTAsync
            Return MyBase.Channel.Dang_nhap_QLCTAsync(Ten_Dang_nhap, Mat_khau)
        End Function
        
        Public Function Dang_nhap_QLCN(ByVal Ten_Dang_nhap As String, ByVal Mat_khau As String) As System.Data.DataSet Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Dang_nhap_QLCN
            Return MyBase.Channel.Dang_nhap_QLCN(Ten_Dang_nhap, Mat_khau)
        End Function
        
        Public Function Dang_nhap_QLCNAsync(ByVal Ten_Dang_nhap As String, ByVal Mat_khau As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Dang_nhap_QLCNAsync
            Return MyBase.Channel.Dang_nhap_QLCNAsync(Ten_Dang_nhap, Mat_khau)
        End Function
        
        Public Function Ghi_moi_Nhan_vien(ByVal Du_lieu_He_khach As System.Data.DataSet) As String Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Ghi_moi_Nhan_vien
            Return MyBase.Channel.Ghi_moi_Nhan_vien(Du_lieu_He_khach)
        End Function
        
        Public Function Ghi_moi_Nhan_vienAsync(ByVal Du_lieu_He_khach As System.Data.DataSet) As System.Threading.Tasks.Task(Of String) Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Ghi_moi_Nhan_vienAsync
            Return MyBase.Channel.Ghi_moi_Nhan_vienAsync(Du_lieu_He_khach)
        End Function
        
        Public Function Cap_nhat_Nhan_vien(ByVal Du_lieu_He_khach As System.Data.DataSet) As String Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Cap_nhat_Nhan_vien
            Return MyBase.Channel.Cap_nhat_Nhan_vien(Du_lieu_He_khach)
        End Function
        
        Public Function Cap_nhat_Nhan_vienAsync(ByVal Du_lieu_He_khach As System.Data.DataSet) As System.Threading.Tasks.Task(Of String) Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Cap_nhat_Nhan_vienAsync
            Return MyBase.Channel.Cap_nhat_Nhan_vienAsync(Du_lieu_He_khach)
        End Function
        
        Public Function Xoa_Nhan_vien(ByVal Du_lieu_He_khach As System.Data.DataSet) As String Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Xoa_Nhan_vien
            Return MyBase.Channel.Xoa_Nhan_vien(Du_lieu_He_khach)
        End Function
        
        Public Function Xoa_Nhan_vienAsync(ByVal Du_lieu_He_khach As System.Data.DataSet) As System.Threading.Tasks.Task(Of String) Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Xoa_Nhan_vienAsync
            Return MyBase.Channel.Xoa_Nhan_vienAsync(Du_lieu_He_khach)
        End Function
    End Class
End Namespace
