//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiemTra02.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public System.Guid UserId { get; set; }
        public string Fullname { get; set; }
        public string PhoneNumber { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingCity { get; set; }
        public string ImagePath { get; set; }
    }
}
