'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace DV_ASMX_Thu_nghiem
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap")>  _
    Public Interface XL_DICH_VU_ASMXSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Doc_Du_lieu", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Doc_Du_lieu() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Doc_Du_lieu", ReplyAction:="*")>  _
        Function Doc_Du_lieuAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface XL_DICH_VU_ASMXSoapChannel
        Inherits DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class XL_DICH_VU_ASMXSoapClient
        Inherits System.ServiceModel.ClientBase(Of DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap)
        Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Doc_Du_lieu() As System.Data.DataSet Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Doc_Du_lieu
            Return MyBase.Channel.Doc_Du_lieu
        End Function
        
        Public Function Doc_Du_lieuAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements DV_ASMX_Thu_nghiem.XL_DICH_VU_ASMXSoap.Doc_Du_lieuAsync
            Return MyBase.Channel.Doc_Du_lieuAsync
        End Function
    End Class
End Namespace
