//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiemTra01_1581270 {
    
    
    public partial class all_product {
        
        /// <summary>
        /// WUC_Sidebar_Category control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KiemTra01_1581270.WUC.WUC_Sidebar_Category WUC_Sidebar_Category;
    }
}
